/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockUSDC__factory } from "./MockUSDC__factory";
export { NFTCollection__factory } from "./NFTCollection__factory";
